# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
                ('alti', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('date', models.DateTimeField(auto_now=True)),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
                ('alti', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaceAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('acronym', models.CharField(max_length=128, verbose_name='Acronym')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('launch_capable', models.BooleanField(default=False, verbose_name='Launch Capable')),
            ],
        ),
        migrations.AddField(
            model_name='satellite',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.SpaceAgency'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='hist',
            field=models.ManyToManyField(to='Sat_Track.SatHistory'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.SpaceAgency', verbose_name='Space Agency'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.Satellite', verbose_name='Object'),
        ),
    ]
