# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
                ('alti', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('date', models.DateTimeField(auto_now=True)),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
                ('alti', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='satellite',
            name='hist',
            field=models.ManyToManyField(to='Sat_Track.SatHistory'),
        ),
    ]
