# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sat_Track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('acronym', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('launch_capable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='astronaut',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.SpaceAgency'),
        ),
        migrations.AddField(
            model_name='astronaut',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.Satellite'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.SpaceAgency'),
        ),
    ]
