# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Sat_Track', '0002_auto_20170706_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.SpaceAgency', verbose_name='Agencja'),
        ),
        migrations.AlterField(
            model_name='astronaut',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='astronaut',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='astronaut',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sat_Track.Satellite', verbose_name='Obiekt'),
        ),
        migrations.AlterField(
            model_name='spaceagency',
            name='acronym',
            field=models.CharField(max_length=128, verbose_name='Akronim'),
        ),
        migrations.AlterField(
            model_name='spaceagency',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Państwo'),
        ),
        migrations.AlterField(
            model_name='spaceagency',
            name='launch_capable',
            field=models.BooleanField(default=False, verbose_name='Może wystrzelić satelitę'),
        ),
        migrations.AlterField(
            model_name='spaceagency',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa'),
        ),
    ]
